internal/thelma/render/render.go
internal/thelma/utils/pool/pool.go
internal/thelma/utils/pool/pool_test.go

For BEEs, we need to sync multiple Argo apps concurrently. This PR refactors the existing worker pool implementation used by `render` in a generic utility package that can also be used by the ArgoCD client package.

DDO-1965 Implementation of the worker pool pattern

---

internal/thelma/app/builder/builder.go
internal/thelma/app/builder/builder_test.go
internal/thelma/app/config/config.go
internal/thelma/app/config/config_test.go
internal/thelma/app/config/options.go
internal/thelma/app/credentials/credentials.go
internal/thelma/app/credentials/testing/testing.go
internal/thelma/app/credentials/token_provider.go
internal/thelma/app/credentials/token_provider_test.go
internal/thelma/app/logging/logging_test.go
internal/thelma/app/scratch/scratch_test.go
internal/thelma/cli/commands/auth/iap/iap_command.go
internal/thelma/clients/iap/iap.go
internal/thelma/clients/iap/token_provider.go
internal/thelma/clients/vault/testing/testing.go
internal/thelma/clients/vault/vault.go
internal/thelma/clients/vault/vault_test.go
internal/thelma/utils/shell/example_test.go
internal/thelma/utils/testutils/testutils.go

* Fix bug in IAP refresh logic (the updated token was not being saved to disk)
* Test coverage for Vault token provider

DDO-1965 Fix bug in IAP refresh logic

---

internal/thelma/bee/bee.go
internal/thelma/cli/commands/bee/pin/pin_command.go
internal/thelma/cli/commands/bee/unpin/unpin_command.go
internal/thelma/cli/commands/bee/vars/vars_command.go
internal/thelma/cli/entrypoint/entrypoint.go
internal/thelma/cli/printing/printer.go
internal/thelma/state/api/terra/environments.go
internal/thelma/state/providers/gitops/clusters.go
internal/thelma/state/providers/gitops/environments.go
internal/thelma/state/providers/gitops/statebucket/statebucket.go
internal/thelma/state/providers/gitops/statebucket/statebucket_smoke_test.go
internal/thelma/tools/argocd/argocd.go
internal/thelma/utils/shell/logging_writer.go
internal/thelma/utils/shell/real_runner.go

* New `thelma bee vars` command
* Generator sync behavior changes

DDO-1966 sync generator after updating bee settings

---

internal/thelma/cli/commands/bee/seed/config.go
internal/thelma/cli/commands/bee/seed/seed/step_2_register_sa_profiles.go

Per https://docs.google.com/document/d/1oemQVjTNjxVcTQdIabyVRWyK4Zt0Rv2B9vkXhbXgWtg/edit?disco=AAAAYXqUMuc

[DDO-2194] Register WSM's SA with Sam during seeding

---

.github/workflows/build.yaml

Fix broken publish workflow (https://github.com/broadinstitute/thelma/runs/7882602999?check_suite_focus=true) introduced by #41

Fix publish workflow

---

internal/thelma/bee/cleanup/cleanup.go

Also delete subscriptions when a topic is deleted

DDO-2403 More pubsub cleanup

---

internal/thelma/app/builder/builder.go

We've already discussed me merging this cut-over unilaterally since I'm intentionally doing it at 1:30am so I can hunt down bugs off-hours.

[DDO-2449] Sherlock as default state provider

---

go.mod
go.sum
internal/thelma/clients/sherlock/state_writer.go
internal/thelma/state/providers/sherlock/state_loader.go

Pull in changes from: https://github.com/broadinstitute/sherlock/pull/112

DDO-2550 Update thelma to use new sherlock client

---

internal/thelma/clients/google/terraapi/firecloudorch.go
internal/thelma/clients/google/terraapi/firecloudorch_test.go

Add INFO messages to indicate success if an orch api call succeeds on retry

DDO-2447 Log clarification

---

internal/thelma/app/metrics/metrics.go
internal/thelma/app/platform/platform.go
internal/thelma/app/platform/platform_test.go
internal/thelma/bee/bee.go
internal/thelma/cli/commands/bees/delete/delete_command.go
internal/thelma/cli/commands/slack/notify/notify_command.go
internal/thelma/clients/slack/slack.go

Send slack notification to #ap-k8s-monitor when the [BEE cleanup job](https://github.com/broadinstitute/terra-github-workflows/actions/workflows/bee-cleanup.yaml) deletes a BEE (or fails to)

DDO-2565 Slack notifications for BEE cleanup

---

internal/thelma/charts/source/charts_dir.go

Ensure that for charts with multiple layers of dependencies `helm dependency update` is called on all nodes in the depdency tree for a given chart. Previously this would only happen if the leaf nodes needed to be published.

Support for Multilayer Dependencies when Publishing Charts

---

internal/thelma/cli/commands/bees/apply_schedule/apply_schedule_command.go

This was on my list but I threw out the code that did it when I moved away from continually applying the schedule, remembered it talked with JM about it just now. I'm not sure if this case will actually come up but it's a small increase in complexity so I feel like it's okay.

[DDO-2669] Add apply-schedule creation buffer

---

internal/thelma/bee/bee.go

[DDO-2695] Fix Slack message typo

---

internal/thelma/app/autoupdate/bootstrap/bootstrap.go
internal/thelma/app/autoupdate/bootstrap/bootstrap_test.go
internal/thelma/app/autoupdate/bootstrap/welcome.go
internal/thelma/app/autoupdate/bootstrap/welcome_test.go
internal/thelma/app/autoupdate/bootstrap/zshrc.go

fix a bug identified by @katiewelch -- thanks!
from:
to:

[DDO-2703] Fix bug in zshrc warning

---

.github/workflows/build.yaml
.github/workflows/test.yaml

Update syntax format for depreciated ```set-output```.

DDO-2648 Update set-output

---

internal/thelma/bee/bee.go
internal/thelma/cli/commands/bee/re_provision/re_provision_command.go
internal/thelma/cli/commands/bee/re_provision/re_provision_command_test.go
internal/thelma/cli/commands/bee/sync/sync_command.go
internal/thelma/cli/commands/bee/sync/sync_command_test.go
internal/thelma/cli/entrypoint/entrypoint.go

Problem:
(Beehive can't do this automatically, there's not a clean thing for it to run to pull this off because it would need to know about the generator)
Solution:
Uh, kinda just provision again? I extracted out some of the meat of the provision function and I think by running that directly it will actually do what we want for both chart additions and deletions? (obviously only for BEEs). Sorta the same pattern as #75, that seemed to work fine when I did that

[DDO-2740] Thelma BEE sync

---

go.mod
go.sum
internal/thelma/clients/sherlock/sherlock_test.go
internal/thelma/clients/sherlock/state_writer.go
internal/thelma/clients/sherlock/state_writer_test.go

Just for some statewriter stuff which isn't actually ever called nowadays but still
Mocks adjusted
This code paths aren't used anymore, I don't think, _and_ these Sherlock endpoints have better test coverage than the old ones and are in use in Beehive just fine

[DDO-3152] Use charts v3 api

---

go.mod
go.sum
internal/thelma/clients/sherlock/sherlock_test.go
internal/thelma/clients/sherlock/state_loader.go
internal/thelma/clients/sherlock/state_writer.go
internal/thelma/clients/sherlock/state_writer_test.go
internal/thelma/state/providers/sherlock/state_loader_test.go

Like https://github.com/broadinstitute/beehive/pull/346 but for Thelma
I think Thelma's built in tests (modified by this PR too) are sufficient.
Low, Beehive is using these endpoints without issue

[DDO-3184] Use Sherlock's v3 cluster endpoints

---

internal/thelma/bee/seed/seed_step_4_register_test_users.go

Reverts broadinstitute/thelma#303

Revert "[DDO-3709] Hacky work-around for recent BEE seed failures"

---

.github/workflows/test.yaml
internal/thelma/clients/github/gha/oidc_issuer_test.go
internal/thelma/utils/utils.go

Remove the smoke test dependency on the thelma-ci SA key by switching to workload identity auth.
https://github.com/broadinstitute/thelma/pull/311

[DDO-3827] Remove thelma-ci sa key secret dependency
