internal/thelma/cli/commands/render/selector/filter_builder.go
internal/thelma/gitops/state_loader.go
internal/thelma/gitops/statefixtures/fixtures/default/statebucket/state.json
internal/thelma/render/helmfile/stateval/stateval_test.go
internal/thelma/utils/shell/real.go

Before this change, swat BEEs were being deployed to the `terra-swatomation` namespace; they need to go to the correct environment namespace.

DDO-1965 Fix bug in Argo app generation for dynamic environments

---

internal/thelma/cli/commands/bee/vars/vars_command.go
internal/thelma/state/providers/gitops/statefixtures/fixtures/default/thelma-home/clusters/terra/terra-qa.yaml

Tweak a comment (unimportant) and the host FQDN generation logic (very important) to use `bee` instead of `preview`

[DDO-2066] preview ➡️  bee

---

internal/thelma/bee/bee.go
internal/thelma/cli/commands/bee/pin/pin_command.go
internal/thelma/cli/commands/bee/unpin/unpin_command.go
internal/thelma/render/helmfile/stateval/argo.go
internal/thelma/render/helmfile/stateval/stateval_test.go
internal/thelma/state/api/terra/environments.go
internal/thelma/state/providers/gitops/statebucket/statebucket.go
internal/thelma/tools/argocd/argocd.go
internal/thelma/tools/argocd/names.go

So, we still need to sync the terra-bee-generator on every deploy in order to update the branch of the dedicated BEE environment generator.
To work around [this bug](https://github.com/argoproj/argo-cd/issues/4505#issuecomment-880271371), I've enabled autosync with prune on the terra-bee-generator app. Now creating a bee will:
* Hard refresh the terra-bee-generator (it has auto-sync + pruning enabled)
* Hard refresh + sync the environment generator
* Hard refresh + sync all apps generated by the environment generator
(The syncing bug is a big issue with the bee generator but less so with the per-environment generator and argo apps.)
Fix an issue where unpinning didn't truly unpin terra-helmfile branches

DDO-2070 Fixes for pinning and sync behavior

---

internal/thelma/app/root/root.go
internal/thelma/render/helmfile/helmfile.go
internal/thelma/render/helmfile/stateval/cluster.go
internal/thelma/render/helmfile/stateval/stateval.go
internal/thelma/render/helmfile/stateval/stateval_test.go

* Make it possible to use `.Values.Cluster.GoogleProject` and `.Values.Cluster.GoogleProjectSuffix` in values templates
* Fix mode on root subdirectories (much 🤦)
* Fix a bug in render log messages where `--app-version` was not being correctly logged (thanks to @em-may for the report)

DDO-2117 New context in state values

---

internal/thelma/cli/commands/bee/create/create_command.go
internal/thelma/cli/commands/bee/delete/delete_command.go
internal/thelma/cli/commands/bee/pin/pin_command.go
internal/thelma/cli/commands/bee/reset/reset_command.go
internal/thelma/cli/commands/bee/seed/seed/seed_command.go
internal/thelma/cli/commands/bee/seed/unseed/unseed_command.go
internal/thelma/cli/commands/bee/unpin/unpin_command.go
internal/thelma/cli/commands/bee/vars/vars_command.go

https://broadinstitute.slack.com/archives/CQ6SL4N5T/p1657637446078659
Maybe we remove this later, once Thelma isn't running in Jenkins a bunch. Or when we rework the Jenkins jobs and they can do input checking.

[DDO-2184] Error if environment name is blank or empty, don't rely on Cobra doing it

---

internal/thelma/cli/commands/bee/seed/config.go

I thought Go would work similarly to every other language, but this is not the case. Can't run a format string with more varargs then you have insertion points, it will just intentionally botch your string.

[DDO-2190] Go is apparently strict with format strings

---

.github/workflows/lint.yaml
internal/thelma/cli/commands/bee/pin/pin_command.go
internal/thelma/cli/commands/bee/unpin/unpin_command.go
internal/thelma/render/helmfile/stateval/environment.go
internal/thelma/render/helmfile/stateval/stateval_test.go
internal/thelma/state/api/terra/environment.go
internal/thelma/state/api/terra/environments.go
internal/thelma/state/providers/gitops/environment.go
internal/thelma/state/providers/gitops/environments.go
internal/thelma/state/providers/gitops/state_loader.go
internal/thelma/state/providers/gitops/statebucket/dynamic_environment.go
internal/thelma/state/providers/gitops/statebucket/dynamic_environment_test.go
internal/thelma/state/providers/gitops/statebucket/schema_verifier.go
internal/thelma/state/providers/gitops/statebucket/statebucket.go
internal/thelma/state/providers/gitops/statebucket/statebucket_smoke_test.go
internal/thelma/state/providers/gitops/statefixtures/fixtures/default/statebucket/state.json
internal/thelma/state/providers/gitops/statefixtures/tests/state_loader_test.go

This PR makes it possible to inject the "currently running CI build number" into Helm config, in order to replicate legacy firecloud-develop behavior: https://github.com/broadinstitute/firecloud-develop/blob/dev/jenkins/jenkins-start-fiab.sh#L134
See [this Slack thread](https://broadinstitute.slack.com/archives/CQ6SL4N5T/p1657120915595579?thread_ts=1654883676.570769&cid=CQ6SL4N5T) for background.
* Add `--build-number` flag to `thelma bee pin`
* Update `thelma bee unpin` to unset build number when it is run
* Make `.Values.Environment.BuildNumber` available in values file templates (it defaults to 0 if not set)

DDO-2167 First pass at adding build number to `helmfile` state values

---

.github/actions/make/action.yaml
.github/workflows/build.yaml
.github/workflows/test.yaml
Dockerfile
Makefile
scripts/sign-and-notarize.sh

This PR adds signing and notarizing for macOS builds. It also adds the following goodies:
* Go deps are now cached between builds
* Builds are parellelized
* The docker build uses the linux release artifact instead of doing another build
Overall this speeds up builds a lot and minimizes the time impact that adding signing/notarizing would otherwise have.
Some notes on time improvements/speed ups, using [this](https://github.com/broadinstitute/thelma/runs/7362013023?check_suite_focus=true) before example and [this](https://github.com/broadinstitute/thelma/actions/runs/2707986760) after example:
* Build times
* Before: 5m 53s
* **After: 1m59s**
* Signing and notarizing:
* Before: N/A
* After: 4m 35s
* Image gen + push + release push:
* Before: 3m 43s
* **After: 1m 47s**
* Total build GHA …

[DDO-2166] Sign and notarize macOS releases + extras!

---

.github/workflows/build.yaml

Turns out caching is hard. Don't release intermediary tarballs.

[DDO-2166] Exclude temp release dirs from GCS uploads

---

internal/thelma/cli/commands/bee/seed/seed/seed_command_test.go
internal/thelma/cli/commands/bee/seed/seed/step_2_register_sa_profiles.go

Ever since we fixed the GCS_NAME_PREFIX, we've been encountering 409 errors during `thelma bee seed`. It turns out some services register their own service accounts (but not super-consistently? Like rawls-qa sometimes appears and sometimes doesn't).
This extremely lazy PR just ignores the 409 errors, which seems to be in line with how the old fiab seeding used to work.
(We could also use Jack's handy `--force` flag, but in that case we're ignoring ALL errors in the entire seeding process)

DDO-2220 Ignore 409 conflicts when registering service accounts

---

internal/thelma/app/app.go
internal/thelma/app/logging/logging.go
internal/thelma/clients/vault/masking_round_tripper.go
internal/thelma/clients/vault/masking_round_tripper_test.go
internal/thelma/clients/vault/testing/testing.go
internal/thelma/clients/vault/vault.go

Implement a [tripperware](https://github.com/improbable-eng/go-httpwares) to automatically mask secrets that are retrieved from Vault.
Thelma has a number of runtime-dependencies on Vault. (The legacy-migrated `bee seed` command, for example, loads a bunch of service account credentials from Vault and uses them to issue requests to Terra.) Now that we are working on making it possible to run Thelma from GitHub actions on DSP's public repos, we need some protection in place to prevent these Vault secrets from leaking in public GHA logs.
We have two choices -- either (1) migrate all those secrets to GitHub secrets (heavy lift) or (2) add leak protection to Thelma itself. This PR implements option 2.
This tripperware is intended for use with the [KV Secret …

DDO-2219 Implement tripperware to automatically mask secrets pulled from Vault

---

internal/thelma/bee/bee.go

We're running 24 services in BEEs, so limiting concurrent syncs to 15 doubles the amount of time we spend waiting for Argo to sync in BEE starts and stops.
If this ends up overwhelming ArgoCD, then we'll look into beefing it up.

[DDO-2222] Remove limit on parallel ArgoCD syncs

---

.github/workflows/build.yaml
internal/thelma/app/logging/logging_test.go
internal/thelma/bee/bee.go
internal/thelma/charts/source/chart.go
internal/thelma/cli/commands/bee/seed/config.go
internal/thelma/cli/commands/bee/seed/seed/step_1_create_elasticsearch.go
internal/thelma/cli/commands/bee/unpin/unpin_command.go
internal/thelma/clients/google/terraapi/terra.go
internal/thelma/clients/vault/masking_round_tripper.go
internal/thelma/clients/vault/testing/testing.go
internal/thelma/render/helmfile/helmfile.go
internal/thelma/render/resolver/remote_resolver.go
internal/thelma/tools/argocd/argocd.go
scripts/checksum.sh
scripts/sign-and-notarize.sh

* [DDO-2247] Explicitly add hermione as a project owner in Agora as part of seed logic (fix broken Rawls & Orch tests)
* [DDO-2138] Stop waiting for terra-bee-generator to become healthy on BEE create, because multiple concurrent bee creates/deletes can prevent this from ever happening. As an alternative, we now wait for the BEE's generator to exist.
* [DDO-2255] Wait for deployments to become healthy after a restart to pick up firecloud-develop changes. We also now only trigger syncs if a hard-refresh diff shows the app as out of sync
* Address linting failures related to [deprecation of `ioutils`](https://www.srcbeat.com/2021/01/golang-ioutil-deprecated/)
* Make Docker image build run in parallel with code signing instead of in serial (image testing was blocked earlier due to a notary …

DDO-2247 Kitchen sink BEE fixes

---

.github/actions/make/action.yaml
go.mod

Updates Thelma to run on the latest go version (1.19). Mainly so we can get access to the new generics features for Thelma

DDO-2355 Update Thelma to run on go 1.19

---

internal/thelma/cli/commands/bee/common/pinflags/parsing.go
internal/thelma/cli/commands/bee/common/pinflags/parsing_test.go

The swatomation pipeline had [some magic](https://github.com/broadinstitute/firecloud-develop/blob/a8573a38698890031444166320db1a857f8a0834/run-context/fiab/scripts/FiaB_configs.sh#L125) for converting git branch names into legal Docker image tags.
This exact same logic is duplicated in the various services' [build.sh scripts](https://github.com/broadinstitute/firecloud-orchestration/blob/dc5fc4549864db255703a514b45ac427c58f24a7/script/build.sh#L30).
The simplest path forward is to replicate this logic in Thelma, so that's what this PR does.
Slack thread for context: https://broadinstitute.slack.com/archives/C029LTN5L80/p1665502394560979
(Yes, yes, this conversion should happen in the build/publish pipelines, but this is much easier)

DDO-2398 Fix for swat pipeline breakage

---

go.mod
go.sum
internal/thelma/bee/bee.go
internal/thelma/bee/cleanup/cleanup.go
internal/thelma/bee/cleanup/cleanup_test.go
internal/thelma/cli/commands/bee/common/builders/builders.go
internal/thelma/clients/google/google.go
internal/thelma/clients/vault/masking_round_tripper.go
internal/thelma/clients/vault/masking_round_tripper_test.go

This change updates Thelma to automatically delete a [hardcoded list](https://github.com/broadinstitute/thelma/blob/edb58b5a4a7e540a3ea9fde4c8cac1b740aa44ba/internal/thelma/bee/cleanup/cleanup.go#L18) of pubsub topics when a BEE is deleted.
This also updates the vault auto-masker to be less aggressive -- we should stop seeing project names like `broad-dsde-qa` masked in logs.
Context: https://broadinstitute.slack.com/archives/CQ6SL4N5T/p1665586880611919

DDO-2403 Clean up pubsub topics when BEEs are deleted

---

internal/thelma/clients/vault/testing/testing.go
internal/thelma/clients/vault/vault.go

When we generate a Vault token, we quickly call `/auth/token/lookup`, ignoring the response, just to see if Vault recognized us. That works fine when the authentication is coming from some high-permissioned account, like one of us, or BroadBot, etc, but if we generate a token directly from an approle like I just implemented in #69, that fails because that entire endpoint isn't allowed.
So what are you supposed to do if you want to check your own token? There's a separate endpoint--`/auth/token/lookup-self`--that does that and only that, and _it_ can be called by the approle we have set up with Argo (I replicated locally). It is otherwise equivalent so I'm just replacing it everywhere.

[DDO-2449] Use a lower-permissioned Vault token check

---

internal/thelma/clients/vault/vault.go

Oversight on my part because I was always doing GET requests locally. Apparently both PUT and GET work for /lookup but only get works for /lookup-self.

[DDO-2449] Use GET for Vault /auth/token/lookup-self

---

internal/thelma/cli/commands/charts/publish/publish_command.go
internal/thelma/clients/clients.go
internal/thelma/clients/iap/iap.go

Turns out that basically every GHA that runs Thelma needs to talk to Sherlock, who would have predicted. Me, I should've predicted that lol and I did not. I don't exactly want to mount a Vault token into every GHA in terra-helmfile so I'm just going to kinda productionalize my little workaround that I did for chart publishing.

[DDO-2449] Allow Thelma to short-circuit IAP client if an environment variable is set

---

internal/thelma/cli/commands/argocd/sync/sync_command.go
internal/thelma/cli/commands/render/render_command_test.go
internal/thelma/cli/selector/enum_flag.go
internal/thelma/cli/selector/flags.go
internal/thelma/cli/selector/flags_test.go
internal/thelma/cli/selector/selector.go
internal/thelma/state/api/terra/destination.go
internal/thelma/state/api/terra/filter/release_filters.go
internal/thelma/state/api/terra/named.go
internal/thelma/state/api/terra/release.go
internal/thelma/state/providers/gitops/release.go
internal/thelma/state/providers/sherlock/release.go

User story: “I would like to be able to run thelma argocd sync --exact-release beehive-dev-dsp-tools”. 
It’s me, I’m the user. 🪄 #makeitso
Basically, passing --exact-release:
1. Acts as if you passed --release ALL
2. Lets you not pass -e/-c even for things like `argocd sync`, because it isn't necessary for uniqueness
3. Filters against the "full name" of the release
For Sherlock state provider, full name is the raw exact name stored in Sherlock. For Gitops, it is `fmt.Sprintf("%s-%s", r.name, r.destination.Name())` to achieve the same effect in all current cases.
Why is this so useful? The entirety of the heavy-lifting of [terra-github-workflows/sync-release.yaml](https://github.com/broadinstitute/terra-github-workflows/blob/main/.github/workflows/sync-release.yaml#L99) can literally just …

[DDO-2457] Add `--exact-release` as a full name alternative to `--release`

---

internal/thelma/bee/bee.go
internal/thelma/cli/commands/bee/provision/provision_command.go
internal/thelma/cli/commands/bee/provision/provision_command_test.go
internal/thelma/cli/entrypoint/entrypoint.go

It's like `thelma bee create` except it doesn't do the create part. The implementation is just splitting the existing internal create function in two and adding a new CLI command that shortcuts to the second part.

[DDO-2461] `thelma bee provision`

---

internal/thelma/bee/bee.go
internal/thelma/cli/commands/bee/provision/provision_command.go

Seed options weren't being parsed on the `bee provision` command.
Also fixes an edge case  issue where Thelma would incorrectly report a container log export error when there really wasn't one.

DDO-2474 Fix for BEE seed not running during provisioning

---

internal/thelma/clients/google/terraapi/terra.go

This panic showed up in GHA earlier today: https://broadinstitute.slack.com/archives/C029LTN5L80/p1669053559481829
```
6:00PM INF unregistering lavender.brown@quality.firecloud.org
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0xc476b1]
goroutine 1 [running]:
github.com/broadinstitute/thelma/internal/thelma/clients/google/terraapi.(*terraClient).doJsonRequest(0xc000a59040, ***0x226f27b?, 0xc000698f10?***, ***0xc00096aa80, 0x58***, ***0x2681600?, 0xc000cf8d80?***)
/home/runner/work/thelma/thelma/internal/thelma/clients/google/terraapi/terra.go:60 +0x1d1
github.com/broadinstitute/thelma/internal/thelma/clients/google/terraapi.(*samClient).UnregisterUser(0xc0005f05b8, ***0xc0006a4570, 0x15***) …
```

DDO-2477 Fix panic in bee unseed

---

internal/thelma/cli/commands/argocd/sync/sync_command.go
internal/thelma/clients/vault/masking_round_tripper.go
internal/thelma/clients/vault/masking_round_tripper_test.go
internal/thelma/ops/status/event_matcher.go
internal/thelma/ops/status/reporter.go
internal/thelma/ops/status/status.go
internal/thelma/ops/sync/sync.go
internal/thelma/tools/argocd/argocd.go
internal/thelma/tools/argocd/argocd_test.go
internal/thelma/tools/argocd/status.go
internal/thelma/tools/argocd/status_test.go
internal/thelma/tools/argocd/testdata/application.yaml
internal/thelma/utils/pool/pool.go
internal/thelma/utils/pool/summarizer.go
internal/thelma/utils/pool/summarizer_test.go

This PR updates thelma's `argocd sync` command so that Argo apps are pointed at the correct* terra-helmfile ref and firecloud-develop ref prior to syncing, using the ArgoCD cli's `argocd app set <name> --revision <rev>` command.
I chose this approach over syncing the generator because it will work for live environments too without (1) causing a huge performance hit (syncing `terra-app-generator` takes, like, several minutes) or (2) having cross-application effects (ONLY the service we are syncing will be impacted).
(*correct in this case means "whatever's in Sherlock")
This PR also includes some small cosmetic changes to Thelma's logging:
* Don't auto-mask secrets that are < 5 characters long, hoping this will reduce some of our spurious redactions in GHA logs
* Reduce the width of sync …

DDO-2476 Propagate git refs from Sherlock into ArgoCD when services are synced

---

internal/thelma/tools/argocd/argocd.go
internal/thelma/tools/argocd/argocd_test.go

This avoids triggering a hard refresh, which we do later anyway, and which can take a lot of time and cause timeouts when ArgoCD is under load.
This is related a [change](https://github.com/broadinstitute/thelma/pull/84) we merged earlier today that lead to timeouts running `argocd app set` when the repo server is under load. Example: https://github.com/broadinstitute/terra-github-workflows/actions/runs/3526454011/jobs/5914394810#logs

DDO-2476 Add --validate=false to `argocd app set`

---

internal/thelma/bee/bee.go
internal/thelma/cli/commands/bee/common/views/bee.go
internal/thelma/ops/status/reporter.go
internal/thelma/ops/status/status.go
internal/thelma/ops/sync/sync.go

Stop including error messages in Status objects, as it can lead to secrets leaking in CI logs.

DDO-2480 Prevent secrets from leaking in CI logs

---

internal/thelma/clients/sherlock/chart_version_updater.go

Little typo I made, just means that https://beehive.dsp-devops.broadinstitute.org/charts/consent/chart-versions/0.63.0 doesn't have https://beehive.dsp-devops.broadinstitute.org/charts/consent/chart-versions/0.62.0 as its parent in Sherlock's database. This will fix that going forward.

[DDO-2489] Fix a Thelma -> Sherlock typo

---

internal/thelma/tools/argocd/argocd.go
internal/thelma/tools/argocd/argocd_test.go

`argocd app get -o name` now lists applications with namespace (`<namespace>/<application>`) instead of just `<application>`)
(ref https://github.com/argoproj/argo-cd/pull/9755)

DDO-2500 fix: argocd cli now prefixes application names with namespace

---

internal/thelma/clients/sherlock/chart_version_updater.go

- it was outputting and actually making an empty request to sherlock when there was nothing to do
- it was referencing the original `chartReleaseSelectors` instead of the new `chartReleasesToRefresh` that I had added inside the function (that's what was actually doing the work but it wasn't appearing in output)

[DDO-2518] Fix chart publish log output

---

internal/thelma/cli/commands/render/render_command.go
internal/thelma/cli/commands/render/render_command_test.go
internal/thelma/render/render.go
internal/thelma/render/validator/validator.go
internal/thelma/tools/kubeconform/kubeconform.go
scripts/install-runtime-deps.sh

Adds support for a `thelma render --validate <ARG>` flag. This is implemented via adding [kubeconfrom](https://github.com/yannh/kubeconform) to Thelma's packaged binaries and then creating it a wrapper for it in the `tools` package. The main uses cases for this new functionality are for use in local helm chart development and as a CI check in terra-helmfile.
`--validate` is implemented as a post render step. Once all the renders for a thelma invocation have finished, kubeconform will then be invoked against the output directly where it will recursively find and validate all k8s manifest yaml files.
The default behavior of this new flag is `skip` which will skip performing any validation. This is to avoid causing failures in existing render processes as well as to avoid adding the runtime …

DDO-2490 K8s Manifest Validation

---

internal/thelma/cli/commands/bee/create/create_command.go

Grasping at straws to try to get TLS provisioning working in bees again. Increasing the wait timeout to 30 mins, due to zerossl having issues

Bump Bee Create Timeout to 30 Minutes due to Zero SSL slowness

---

go.mod
go.sum
internal/thelma/clients/google/terraapi/firecloudorch.go
internal/thelma/clients/google/terraapi/firecloudorch_test.go
internal/thelma/clients/kubernetes/kubecfg/kubecfg_test.go
internal/thelma/utils/testutils/fake_token_source.go

This change updates Thelma's firecloud-orchestration client to retry failed requests that include an error message matching `java.net.UnknownHostException` or `java.net.SocketTimeoutException`.
Failed requests will be retried every 30 seconds for up to 20 minutes. The long timeout is to help us determine if these issues eventually resolve on their own, or if more aggressive intervention (say, restarting orch  or its dependencies), is required.
The BEE seeding process sometimes fails with errors from Orch like this:
```
Class":"akka.stream.StreamTcpException","message":"Tcp command 
[Connect(thurloe.jenkins-swat-72360.bee.envs-terra.bio/<unresolved>:443,None,List(),
Some(20 seconds),true)] 
failed because of java.net.UnknownHostException: thurloe.jenkins-swat-72360.bee.envs-terra.bio"
``` …

DDO-2447 Retry failed orch requests during seeding

---

internal/thelma/clients/google/terraapi/firecloudorch.go

Add regexps matching:
```
11:42:22 #1: 500 Internal Server Error from 
https://firecloudorch.jenkins-swat-leo-6269.bee.envs-terra.bio/register/profile 
({"causes":[],
"exceptionClass":"akka.http.impl.engine.client.OutgoingConnectionBlueprint$UnexpectedConnectionClosureException",
"message":"The http server closed the connection unexpectedly before delivering responses for 1 outstanding requests",
"source":"Thurloe",
...
```
(encountered [here](https://fc-jenkins.dsp-techops.broadinstitute.org/job/fiab-start/88570/console))
and
```
17:51:51   "message": "ErrorReport(Agora,<html>\r\n<head><title>503 Service Temporarily Unavailable</title></head>\r\n<body>\r\n<center><h1>503 Service Temporarily Unavailable</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r\n,Some(503 Service …
```

DDO-2447 Add another exception to the list of retryables for requests to firecloud-orchestration

---

internal/thelma/clients/slack/slack.go

Thelma doesn't actually fail if it can't send Slack messages, but it does print the warning to console. In Jenkins, Thelma fails this step with a Vault-deny error, and a lot of folks assume that _that's_ the true source of the job erroring (not that the BEE failed to start). I'm thinking that by just swallowing the internal error folks will look at the BEE start error.

[DDO-2617] Hide Thelma Slack errors more

---

go.mod
go.sum
internal/thelma/charts/source/chart.go
internal/thelma/render/resolver/local_resolver.go
internal/thelma/render/resolver/resolver_test.go
internal/thelma/render/resolver/testdata/charts/fakechart/Chart.yaml
internal/thelma/render/resolver/testdata/charts/fakechartdep1/Chart.yaml
internal/thelma/render/resolver/testdata/charts/fakechartdep2/Chart.yaml

A workaround for [this old issue](https://github.com/helm/helm/issues/2247) in helm. The new `foundation` helm chart has multiple layers of dependencies, currently the `localResolver` used in `development` mode only performs `helm dendency update` on the top level parent chart.
Following this change the local resolver will now determine all the dependencies of a parent chart that exist in the `sourceDir` and run `helm dependency update` on each of them in topological ordering. 
Example Debug log output from a render showing this in action

DDO-2658 Add Support For Multi-Layer Helm Depedency Updates in Local Resolver

---

Dockerfile
Makefile
internal/thelma/app/root/releases_dir.go
internal/thelma/app/root/releases_dir_test.go
internal/thelma/app/root/root.go
internal/thelma/app/root/tools_dir.go
internal/thelma/app/root/tools_dir_test.go
scripts/sign-and-notarize.sh

In the release archive and Docker images, move Thelma's tools into a separate directory from the main thelma binary.
Th is allows developers to have Thelma on PATH without shadowing existing local installations of Helm, Kubectl, etc.

DDO-2626 Prepare to break tools into separate directory

---

internal/thelma/cli/commands/bees/apply_schedule/apply_schedule_command.go

So the schedule screwed up because some BEEs are in a broken state. It stopped some but not all. I suspect it will start some but not all in the morning.
This PR tackles that issue in two ways:
- First, don't exit if there was an error applying the schedule for one of the BEEs. I didn't realize this wasn't the default for pool, my bad.
- Second, don't wait for the BEEs to be healthy because we kinda don't care. We care about them being synced; I don't think we want this job throwing errors if a dev leaves their BEE in a broken state at the end of the day.

[DDO-2669] Continue applying schedule even if a BEE errors

---

internal/thelma/app/autoupdate/bootstrap/welcome_test.go
internal/thelma/app/logging/logging.go
internal/thelma/app/logging/logging_test.go
internal/thelma/utils/wordwrap/wordwrap_test.go

Small misc PR I forgot to push earlier this week.
* Fix an issue where word-wrapped console logs are misaligned if the current 12-hour time begins with a single digit.
* Add `pid` to Thelma's debug logs, so it's easier to distinguish between individual Thelma runs
* Add a testcase to the wordwrap package that includes emoji

[DDO-2683] Minor logging adjustments

---

scripts/install-runtime-deps.sh

I'm starting to do some experimentation with having thelma talk to azure k8s clusters related to new service spin up projects. Connecting to the k8s api using user identities in Azure requires [this kubectl plugin](https://github.com/Azure/kubelogin/) (similar to how gke also requires one).
This will also be needed for the azure implementation of `sql connect` when we are ready for that.
Unfortunately the release for the plugin are published as zip archive rather than a tarball :(

Add Azure Kubelogin Kubectl Plugin To Runtime Deps

---

internal/thelma/bee/bee.go
internal/thelma/cli/commands/bee/pin/pin_command.go

Lots of context in [this slack thread](https://broadinstitute.slack.com/archives/CQ6SL4N5T/p1681408772749069), but basically there is a bug in thelma where PR branch version pins supplied to `thelma bee create` don't stick.
Thanks to @em-may for the report!
Tested by creating a bee locally, the correct settings are propagating now.

[DDO-2779] bugfix: reload state after version pinning

---

internal/thelma/render/resolver/cache.go
internal/thelma/render/resolver/local_resolver.go
internal/thelma/render/resolver/remote_resolver.go
internal/thelma/render/resolver/resolved_chart.go
internal/thelma/render/resolver/resolved_chart_test.go
internal/thelma/render/resolver/resolver.go
internal/thelma/render/resolver/resolver_test.go
internal/thelma/render/resolver/testdata/charts/fakechart1/Chart.yaml
internal/thelma/render/resolver/testdata/charts/fakechart2/Chart.yaml

Solves the issue discussed [here](https://broadinstitute.slack.com/archives/CQ6SL4N5T/p1683126783453789) by being a lot smarter about how we run `helm dependency update`. We now cache that at a "per chart directory on disk" level, rather than "per top level released chart" like we were effectively doing before. 
Managed to write a mocked unit test for this! Basically we can tell that the caching is working because we skip a `helm dependency update` for dependency of another chart. Can't quite test the fact that this helps with thread-safety from a unit test, but the behavior works.
- [b94b2d0](https://github.com/broadinstitute/thelma/pull/136/commits/b94b2d0f24331e739aeb5cf1cb4bae065fe310eb) adds a test that passes for the old not-ideal behavior.
- …

[DDO-2816] Don't rerun `helm dependency update` on dependencies

---

internal/thelma/bee/seed/seed_step_2_register_sa_profiles.go

Sam is returning a response like this when seeding app sa users results in 409:
```
409 Conflict from https://firecloudorch.jenkins-swat-leo-8316.bee.envs-terra.bio/register/profile ({"causes":[{"causes":[],"message":"user sam-qa@broad-dsde-qa.iam.gserviceaccount.com is already registered","source":"sam","stackTrace":[],"statusCode":409}],"message":"user sam-qa@broad-dsde-qa.iam.gserviceaccount.com is already registered","source":"Sam","stackTrace":[],"statusCode":409})
```
This message does not match regex handling that was used to ignore 409s so thelma was still erroring out on 409s with the above message.
I also tested the updated regex against the error with an online regex tool.
I've tested this by running a bee provision with thelma locally built from this branch. The error does …

DDO-2836 Update Regex For Ignoring 409s in Bee Seeding

---

.golangci.yaml
internal/thelma/charts/source/charts_dir.go

Fix the bug reported here: https://broadinstitute.slack.com/archives/CADM7MZ35/p1684255219101189
Also try to reduce runtime for golangci-lint runs by excluding generated mocks/ packages from linting.
This change is trivial and will only impact chart publishing workflows, so I am comfortable merging as-is.

[DDO-2853] Render READMEs after bumping chart version

---

internal/thelma/clients/iap/iap.go

Hit https://sherlock.dsp-devops.broadinstitute.org/swagger/index.html#/Misc/get_connection_check so it doesn't show up as a 404 in Sherlock's logs.
I did `make build` and then `./output/bin/thelma render -r leonardo -e prod`, it got an IAP credential without issue. Can hit https://sherlock.dsp-devops.broadinstitute.org/connection-check in the browser too.

[DDO-2961] Use Sherlock's /connection-check

---

internal/thelma/clients/google/terraapi/firecloudorch.go

Add a retry for an annoying [bee seeding failure](https://fc-jenkins.dsp-techops.broadinstitute.org/job/fiab-start/95595/console)
```
14:01:56 #1: 503 Service Unavailable from https://firecloudorch.jenkins-swat-77525.bee.envs-terra.bio/register/profile ({"causes":[],"message":"The server was not able to produce a timely response to your request.\r\nPlease try again in a short while!","source":"Sam","stackTrace":[],"statusCode":503})
```

DDO-2946 Add another retry condition for orch errors

---

internal/thelma/clients/google/terraapi/firecloudorch.go
internal/thelma/clients/google/terraapi/firecloudorch_test.go

There are numerous different errors that happen during bee seeding that appear as errors from the orchestration. Enumerating all the different possible errors here and handling them individually is impossible they can range from errors sourced from any terra service to transient k8s networking issues. So instead we just retry any error. 
This was tested by provisioning a bee from this branch with a local build of thelma.

DDO-3015 Retry all orch bee seeding errors

---

internal/thelma/clients/google/terraapi/firecloudorch.go
internal/thelma/clients/google/terraapi/firecloudorch_test.go

This PR https://github.com/broadinstitute/thelma/pull/145 made Bee provisioning more stable, but it also caused it to take longer, because known 409 Conflict errors occur when registering some Bee service accounts. See, for example, [this Bee create run](https://github.com/broadinstitute/terra-github-workflows/actions/runs/5795701222/job/15707784868), that retried a 409 Conflict error for 20 minutes:
```
10:50 WRN POST https://firecloudorch.leonardo-5795591422-1-dev.bee.envs-terra.bio/register/profile failed (attempt 39 of 40): 409 Conflict from https://firecloudorch.leonardo-5795591422-1-dev.bee.envs-terra.bio/register/profile (***"causes":[***"causes":[],"message":"user sam-qa@broad-dsde-qa.iam.gserviceaccount.com is already registered","source":"sam","stackTrace":[],"statusCode":409***] …
```

DDO-3015 bee seeding: Retry all orch errors EXCEPT 409 conflicts

---

internal/thelma/ops/status/event_matcher.go

[This panic](https://github.com/broadinstitute/thelma/blob/a25c94b1764d3e396949f4c6a3f0535da2dcc13a/internal/thelma/ops/status/event_matcher.go#L36) was triggered by a Jenkins job today:
https://fc-jenkins.dsp-techops.broadinstitute.org/job/fiab-start/96310/console
```
15:36:26 19:36 INF martha:           queued
15:36:26 19:36 INF mongodb:          queued
15:36:26 19:36 INF ncbiaccess:       queued
15:36:26 19:36 INF ontology:         queued
15:36:26 19:36 INF rawls:            queued
15:36:26 19:36 INF sam:              queued
15:36:26 19:36 INF terraui:          queued
15:36:26 19:36 INF thurloe:          queued
15:36:26 19:36 INF tsps:             queued
15:36:26 19:36 INF workspacemanager: queued
15:36:26 19:36 INF Check status in ArgoCD at …
```

[DDO-3042] Replace a panic with a warning

---

internal/thelma/clients/sherlock/sherlock.go
internal/thelma/clients/sherlock/sherlock_test.go

Makes it so that if you set a `SHERLOCK_GHA_OIDC_TOKEN` environment variable, Thelma will pass the value of it in all requests made to Sherlock in the `X-GHA-OIDC-JWT` header.
We can use this in terra-helmfile to make new chart versions be deployed to dev as the people who merge the PRs, instead of the SA that Thelma runs as.
Added tests for both cases and improved testing around validating that the IAP token is getting passed to.
Very low

[DDO-3130] Allow passing X-GHA-OIDC-JWT header to Sherlock

---

internal/thelma/app/config/config.go
internal/thelma/app/config/config_test.go
internal/thelma/app/config/profiles/ci.yaml
internal/thelma/app/logging/logging.go
internal/thelma/app/logging/logging_test.go
internal/thelma/cli/entrypoint/entrypoint.go

I was struggling to trace a mysterious error today (seemed to be related to networking struggles), so decided to bite the bullet and add stack traces for errors in Thelma.
Error traces are disabled by default. They can be turned using the `logging.errtrace.enabled` config key, for example by setting the env var `THELMA_LOGGING_ERRTRACE_ENABLED=true`.
Note that in order for stacktraces to work, errors need to be created using the `github.com/pkg/errors` packge. See ZeroLog docs for more details. I will submit a future PR to bulk find-replace all instances of `fmt.Errorf` with `errors.Errorf`.
Here's example console log output:
```
1:24PM ERR test error=test stack=[{"func":"foo","line":"62","source":"entrypoint.go"},{"func":"bar","line":"72","source":"entrypoint.go"},{"func":"baz","line":"77 …
```

[DDO-3139] Optional stacktraces for Thelma errors

---

.golangci.yaml
internal/thelma/charts/changedfiles/changedfiles.go
internal/thelma/charts/changedfiles/changedfiles_test.go
internal/thelma/charts/changedfiles/testdata/charts/agora/Chart.yaml
internal/thelma/charts/changedfiles/testdata/charts/foundation/Chart.yaml
internal/thelma/charts/changedfiles/testdata/charts/ingress/Chart.yaml
internal/thelma/charts/changedfiles/testdata/charts/mysql/Chart.yaml
internal/thelma/charts/changedfiles/testdata/charts/postgres/Chart.yaml
internal/thelma/charts/changedfiles/testdata/charts/rawls/Chart.yaml
internal/thelma/charts/changedfiles/testdata/charts/sam/Chart.yaml
internal/thelma/charts/changedfiles/testdata/charts/secrets-manager/Chart.yaml
internal/thelma/charts/changedfiles/testdata/charts/workspacemanager/Chart.yaml
internal/thelma/charts/changedfiles/testdata/charts/yale/Chart.yaml
internal/thelma/charts/changedfiles/testdata/statefixture.yaml
internal/thelma/cli/commands/charts/publish/publish_command.go
internal/thelma/cli/commands/render/render_command.go
internal/thelma/cli/commands/render/render_command_test.go
internal/thelma/cli/selector/changed_files_flag.go
internal/thelma/cli/selector/enum_flags.go
internal/thelma/cli/selector/render_selector.go
internal/thelma/cli/selector/render_selector_test.go
internal/thelma/cli/selector/selector.go
internal/thelma/state/api/terra/filter.go
internal/thelma/state/api/terra/filter/destination_filter.go
internal/thelma/state/api/terra/filter/environment_filter.go
internal/thelma/state/api/terra/filter/release_filter.go
internal/thelma/state/api/terra/filter/release_filters.go
internal/thelma/state/api/terra/filter/strings.go

This PR adds a new flag, `--changed-files-list=path/to/list.txt`, to the `thelma render` and `thelma charts publish` commands. A changed files list is file that contains a newline-separated list of files that have been changed by a PR. Example contents:
```
charts/leonardo/templates/deployment.yaml
helmfile.yaml
values/app/datarepo/live.yaml.gotmpl
```
Paths in the changed files list should be relative to the root of terra-helmfile.
In the case of `thelma charts publish`, the changed files list will be used to determine a list of charts that should be published from a given PR. In the case of `thelma render`, the changed files list will be used to determine the set of manifests that should be rendered.
* Changes to `charts/<chartname>/*` or `values/(app|cluster)/<chartname>*` will trigger …

[DDO-3139] New `--changed-files-list` argument

---

internal/thelma/cli/commands/render/render_command.go
internal/thelma/cli/commands/render/render_command_test.go
internal/thelma/cli/commands/render/wrapper.go

Add new `--exit-zero-no-matching-releases` option to `thelma render`.
This is a follow-up to #159. By default, `thelma render` exits with an error if no Sherlock releases match its command-line arguments. This is good default behavior -- it's clear for users, and it's a backstop that prevents ArgoCD from deleting resources in the event of a misconfiguration. However, this is not the behavior we want on a terra-helmfile pull request -- if the PR doesn't update any chart or values files, `thelma render` should simply render nothing and exit instead of returning an error.
This PR includes unit tests. I also tested manually locally:
```
$ ./output/bin/thelma render --changed-files-list=/tmp/empty.txt
09:50 ERR error="0 releases matched command-line arguments, nothing to render"
$ echo $?
1
$ …
```

[DDO-3139] Add new `--exit-zero-no-matching-releases` flag to `thelma render`

---

internal/thelma/app/metrics/labels/labels.go
internal/thelma/app/metrics/labels/labels_test.go

Previously Thelma was using the metric label `cluster` to report which cluster an operation was performed against. However this value was being overwritten by Thanos reporting which cluster the prometheus push gateway resides in..
This PR changes the label used by thelma to `target_cluster` so that this info will be preserved.

Rename Metric Cluster Label to Target Cluster

---

internal/thelma/bee/bee.go

Chelsea said it was fine to just hardcode the link because this part of the code doesn't have any easy access to the config mechanism (and we don't really use it for consts in Thelma's codebase anyway)
Small enough change I didn't want to go to the effort but I can if someone feels strongly. Link syntax is the same as used right above on line 198.
Very low, just appending to a string

[DDO-3157] Improve the new BEE slack message

---

internal/thelma/ops/status/reporter.go

The ignoreable "disabling rich status reports" warning adds a ton of noise to sync-release logs for live environments. It would be great to figure out a solution to connecting to the live clusters from GHA some day, but in the mean time let's address the noise.

[DDO-3176] Clean up noisy warning

---

internal/thelma/cli/commands/argocd/sync/sync_command.go

Gary and I noticed queueing during today's staging promotion, which slows down the release process. I think I originally picked the number 15 based on "number of services we currently have in Terra prod". This PR doubles to 30, we can always reduce if ArgoCD starts to fall over.

[DDO-3177] Bump default number of argo apps Thelma syncs in parallel

---

internal/thelma/cli/commands/bee/common/pinflags/pinflags.go
internal/thelma/cli/commands/bee/common/views/bee.go
internal/thelma/cli/commands/render/render_command.go
internal/thelma/cli/commands/render/render_command_test.go
internal/thelma/render/helmfile/helmfile.go
internal/thelma/render/helmfile/stateval/release.go
internal/thelma/state/api/terra/app_release.go
internal/thelma/state/api/terra/mocks/cluster_release.go
internal/thelma/state/api/terra/mocks/release.go
internal/thelma/state/api/terra/release.go
internal/thelma/state/providers/sherlock/app_release.go
internal/thelma/state/providers/sherlock/release.go
internal/thelma/state/providers/sherlock/state_loader.go
internal/thelma/state/providers/sherlock/state_loader_test.go
internal/thelma/state/testing/statefixtures/builder.go
internal/thelma/state/testing/statefixtures/fixtures/default.yaml
internal/thelma/state/testing/statefixtures/tests/statefixtures_test.go

This PR adds support for passing app versions from Sherlock to charts for "cluster releases" (releases like Yale that do not belong to a Terra environment). We already do this for application charts; deploying services like Yale, Sherlock, and Beehive has been a huge pain because we can't leverage the same feature.
* Make `AppVersion` an attribute of the `terra.Release` interface instead of `terra.AppRelease`
* Regenerate mocks and update references to the above
* Update Sherlock state provider to match new interface
* Update Sherlock state loader to include AppVersion on charts loaded from Sherlock
* Update `helmfile` package to include AppVersion in state values for cluster releases
* Remove validation on render command that ensures `--app-version` is not set for `--cluster-releases`
I …

[DDO-3212] Supply AppVersion to cluster release charts

---

internal/thelma/render/helmfile/argocd/argocd.go
internal/thelma/render/helmfile/argocd/argocd_test.go

Check out the original implementation of argoDestinationsForEnvironment and you'll notice that it handles environments existing across multiple clusters -- it reads cluster addresses out of the releases themselves -- but [it ignores the namespace of those releases and assumes it'll match that of the environment](https://github.com/broadinstitute/thelma/blob/main/internal/thelma/render/helmfile/argocd/argocd.go#L72).
Fair assumption... one that I'm now breaking. [datarepo-dev](https://beehive.dsp-devops.broadinstitute.org/clusters/datarepo-dev/chart-releases/dev/datarepo) exists in the dev environment, but in the `dev` namespace, not `terra-dev`.
Luckily, I guess, I didn't know about that assumption when I built the corresponding parts of Sherlock and Beehive, so the rest of our platform …

[DDO-3239] Tell ArgoCD to allow environments across multiple namespaces

---

internal/thelma/bee/seed/seed_step_2_register_sa_profiles.go
internal/thelma/bee/seed/seed_step_4_register_test_users.go
internal/thelma/bee/seed/seeder.go
internal/thelma/bee/seed/unseed_step_1_unregister_all_users.go
internal/thelma/cli/commands/bee/common/seedflags/seedflags.go
internal/thelma/cli/commands/bee/common/unseedflags/unseedflags.go
internal/thelma/clients/google/terraapi/terra.go

**I'm calling this a five-minute speed up**
1. Adds `--registration-parallelism=N` CLI arg to seed and unseed commands ([9b6e838](https://github.com/broadinstitute/thelma/pull/189/commits/9b6e838f6c2961264549eeddfc53ffe798045470))
2. Make the `terra` package play nice with the `pool` package (`terra.TerraClient` can now accept a `pool.StatusReporter`, which it will use for retry output instead of `log` when present) ([e672965](https://github.com/broadinstitute/thelma/pull/189/commits/e672965ab9d0c11b35a7ae9d4c0a8f60dc6a69bd))
3. Parallelize seeding step 2, registering SAs with orch ([f9baf0a](https://github.com/broadinstitute/thelma/pull/189/commits/f9baf0ab5253c636da23838fe5754815a6c513cb)) **(minute -> 20 seconds, YMMV)**
4. Parallelize seeding step 4, registering test users with orch …

[DDO-3303] Parallelize BEE Seeding

---

internal/thelma/bee/bee.go

1. Slack messages now tell you if the BEE actually came up or not (used to say that it was always "ready to go")
2. Slack messages will be sent in more cases (the provision function no longer bails out early, it just skips subsequent steps if there was an error)
Provisioned a BEE with this build, shut down Sam during seeding to force an error.
Very low

[DDO-3313] Improve Slack messages sent when a BEE fails to come up

---

internal/thelma/app/credentials/credentials.go
internal/thelma/app/credentials/token_provider.go
internal/thelma/app/credentials/token_provider_test.go
internal/thelma/clients/github/github.go
internal/thelma/clients/iap/iap.go
internal/thelma/clients/vault/vault.go

#197 made TokenProvider safe for use in goroutines, but only if everything was pointing at the same TokenProvider for a given identifying key ("vault-token", "github-repo-pat", etc).
Turns out there's a few places in Thelma that call NewTokenProvider under the hood, making a new TokenProvider for the same identifying key, environment variables, and on-disk storage. This used to be totally fine because it was single-threaded anyway, and it was looking at the same state.
Now, though, that breaks the goroutine-safety of TokenProvider. This PR renames the function to GetTokenProvider and makes it goroutine-safe and adds caching (so all existing calls will work just as before, just routed through the same TokenProvider instances).
Added a test for the concurrency/caching on GetTokenProvider …

[DDO-3327] Make the GetTokenProvider safe for re-use

---

.github/workflows/build.yaml
.github/workflows/test.yaml

Thelma's workflows use secrets that dependabot PRs don't have. This change skips things that require those secrets within dependabot PRs to hopefully make their CI pass.
The workflows passed below, can't test how dependabot will execute them until it does.
None

[DDO-3357] Make Dependabot work

---

internal/thelma/clients/github/gha/oidc_issuer.go
internal/thelma/clients/github/gha/oidc_issuer_test.go

I admittedly forgot that JSON doesn't have a []bytes type so "binary data" would be represented as a base64 string. The right thing to do is parse this as a string, [as GitHub's own package for doing this does](https://github.com/actions/toolkit/blob/main/packages/core/src/oidc-utils.ts#L8) 
Can't test this, but it's failing currently without effect so not big deal. You can see the failures if you turn on trace-level debugging in terra-github-workflows (workflows there actually don't get the OIDC token right now, go figure)

[DDO-3356] Parse GitHub's OIDC response `.value` as a string specifically

---

internal/thelma/app/credentials/token_provider.go
internal/thelma/app/credentials/token_provider_test.go
internal/thelma/app/credentials/typed_token_provider.go
internal/thelma/app/credentials/typed_token_provider_test.go

TokenProvider reads `[]byte` from disk and returns the same `[]byte` from Get().
A semi-common pattern in more complex auth providers in Thelma, though, is to:
1. internally parse that `[]byte` to some other type for validation purposes
2. return some subset of that type as the `byte` from Get()
This is done manually with the delegate pattern from the sites where that functionality is necessary.
This PR introduces a GetTypedTokenProvider similar to GetTokenProvider except it requires marshal/unmarshal functions and in return makes the standard validate/refresh/issue functions work with that generic type instead. There's an optional "return this subset from Get()" function as well.
This PR is thoroughly tested but the code isn't used anywhere yet -- using it in the IAP code will require …

[DDO-3360] Typed TokenProvider

---

internal/thelma/clients/clients.go
internal/thelma/clients/google/google.go

Turns out these never get used -- figured I'd split this out
Tests pass, builds pass. Simple refactoring
None

[DDO-3364] Remove superfluous inputs to Google client

---

internal/thelma/toolbox/argocd/argocd.go
internal/thelma/toolbox/argocd/argocd_test.go

Increase the default post-sync wait-healthy timeout from 10 minutes to 15 minutes.

[DDO-3376] Increase wait healthy timeout

---

internal/thelma/app/config/profile.go
internal/thelma/app/config/profiles/gha.yaml
internal/thelma/clients/clients.go
internal/thelma/clients/google/google.go
internal/thelma/clients/google/mocks/clients.go
internal/thelma/clients/iap/google-provider.go
internal/thelma/clients/iap/iap.go

Adds a new IAP mechanism, `google`, in addition to `workloadidentity` and `browser`. It borrows Thelma's Google authentication to generate an IAP token that way. That'll only work if Thelma's Google auth is a service account. It only gets called by a new special profile, `gha` (so all the existing `ci` usages/autodetection won't trigger these new code paths).
Some test coverage in-codebase where possible, but I manually tested this.
This PR uses new Thelma with the GHA profile (and modifications to make that work -- just auth with `thelma-ci` when using Thelma instead of using different accounts for different parts of Thelma). As soon as this PR is merged, I'm going to get that one ready to be merged (undo the "manually use this Thelma version" change)
[This …

[DDO-3383] Allow generating IAP tokens with Google authentication

---

internal/thelma/charts/deploy/config.go
internal/thelma/charts/deploy/config_test.go
internal/thelma/charts/deploy/deployer.go
internal/thelma/charts/deploy/deployer_test.go
internal/thelma/charts/releaser/deployed_version_updater.go
internal/thelma/charts/releaser/deployed_version_updater_test.go
internal/thelma/charts/releaser/releaser.go
internal/thelma/charts/releaser/releaser_test.go
internal/thelma/cli/commands/charts/deploy/deploy_command.go
internal/thelma/cli/commands/charts/publish/publish_command.go
internal/thelma/cli/commands/charts/sherlockflags/sherlockflags.go
internal/thelma/clients/sherlock/chart_version_updater.go
internal/thelma/clients/sherlock/mocks/chart_version_updater.go
internal/thelma/clients/sherlock/mocks/sherlock.go
internal/thelma/utils/stateutils/stateutils.go

@em-may ran into a bug this morning where a new chart version was not reported for the `vaultcopy` chart.
This was a logical error; the `thelma charts publish` command needs to report new versions while the `thelma charts deploy` needs to update chart releases to use new versions.
This PR fixes the issue by adding the appropriate functionality to each command.

[DDO-3282] Bugfix: Report new chart versions even if not deploying

---

internal/thelma/charts/deploy/config_test.go
internal/thelma/charts/deploy/deployer.go
internal/thelma/charts/releaser/deployed_version_updater_test.go
internal/thelma/clients/sherlock/chart_version_updater.go

Yet another issue with the new post-publish deploy workflow.
[This fix](https://github.com/broadinstitute/thelma/pull/231) is causing an issue where data plane charts such as WDS, that do not have a corresponding chart in Sherlock, are failing to publish.
This PR updates the Sherlock chart version publishing code to check if the chart exists in Sherlock before attempting to report a new version.
Before my changes to support post-publish deploys, this corner of Thelma code made a best-effort attempt to report charts to sherlock but basically suppressed any errors it encountered. I removed the error suppression because I wanted to report unexpected errors appropriately, and this has exposed two cases that didn't occur to me to test:
* charts that exist in terra-helmfile have no `Chart` …

[DDO-3282] Bugfix: Fix for data plane charts such as `wds`

---

internal/thelma/bee/bee.go
internal/thelma/charts/changedfiles/changedfiles.go
internal/thelma/cli/commands/sql/sqlhelpers/command.go
internal/thelma/cli/selector/enum_flags.go
internal/thelma/cli/selector/filter_builder.go
internal/thelma/state/api/terra/destinations.go
internal/thelma/state/api/terra/environments.go
internal/thelma/state/api/terra/filter/environment_filters.go
internal/thelma/state/api/terra/filter/environment_filters_test.go
internal/thelma/state/api/terra/mocks/destinations.go
internal/thelma/state/api/terra/mocks/environments.go
internal/thelma/state/api/terra/mocks/releases.go
internal/thelma/state/api/terra/releases.go
internal/thelma/state/providers/sherlock/destinations.go
internal/thelma/state/providers/sherlock/environments.go
internal/thelma/state/providers/sherlock/releases.go
internal/thelma/state/providers/sherlock/state_exporter_writer.go
internal/thelma/state/testing/statefixtures/tests/statefixtures_test.go

Since I'm touching Thelma, take a stab at [the first bullet in the Thelma state cleanup design doc](https://docs.google.com/document/d/1LDQwYbTJPzEpf-xHmXPNX7T0qJkdVy2xD23xELeNJf4/edit?usp=sharing). This task involves removing Filter() methods from the state interface, since they assume all state information is available locally.
In addition to making sure the linter and unit tests pass, I created a Bee with my locally-compiled Thelma to make sure all worked as expected.

[DDO-3437] Remove `Filter()` from state interfaces

---

go.mod
go.sum

Bump Thelma's usage of the client library to https://github.com/broadinstitute/sherlock/pull/484
CI passes (so there's no usage of the removed stuff in the client library) so that's enough by me
Very low

[DDO-3470] Bump Sherlock dependency to v1.0.0

---

internal/thelma/clients/github/gha/oidc_verifier.go

I'm not positive that this is the true error people are seeing, but it seems like a fine thing to harden in a simple way.
If there's an error, we wait a second, try again, and then act based on the error-ness of the second invocation. That should theoretically help with truly transient errors when the verifier tries to connect to GitHub's OIDC description endpoint.
Uh, none, I'm not even sure how to test this. But it can't be worse than how it works now, in my opinion.
Low?

[DDO-3486] Retry initializing the GHA OIDC verifier

---

argocd/plugin.yaml

I realized pretty quickly that since ArgoCD requires all plugins to use stdout, we always would need to set `PARAM_STDOUT=true` or the plugin would fail. Might as well specify the command line argument. 
The stdout parameter was already omitted in the plugin documentation because earlier-me was like "it'll always have the same value, no need to document it." I think it slipped my mind that the default is false.
None (but this is a non-code change, this plugin isn't currently used)
None

[DDO-3575] ArgoCD plugin: always use --stdout

---

internal/thelma/app/config/profiles/argocd.yaml

https://argo-cd.readthedocs.io/en/stable/operator-manual/config-management-plugins/#write-the-plugin-configuration-file notes that plugins are always run from the root of the "Application"'s repository. For us, that'll always be configured as terra-helmfile. 
Rather than leaving up the gotcha of making sure we set `THELMA_HOME=.` or something in the Kubernetes sidecar config, I'm adding it to the argocd profile (which we still need to set manually, but one gotcha is better than two).
None, profile unused (but note that [config.go](https://github.com/broadinstitute/thelma/blob/b82cb2fcef75098723c5d2f5dcb9c22f2941b097/internal/thelma/app/config/config.go#L104-L104) specifically allows setting this from config file and it resolves relative paths to absolute based on the current working …

[DDO-3575] ArgoCD plugin: set THELMA_HOME to current working directory

---

argocd/plugin.yaml
internal/thelma/cli/commands/render/render_command.go
internal/thelma/cli/commands/render/render_command_test.go

Adds a `thelma render --mode=argocd-auto` flag with [logic](https://github.com/broadinstitute/thelma/pull/285/files#diff-b5649879a47c4894e58600c6f28ac624840f30770280f130d6d9eb6a74b269dfR313) that exactly mirrors what the [bash shim](https://github.com/broadinstitute/terra-helmfile/blob/master/charts/dsp-argocd/plugin-scripts/terra-helmfile-app.sh#L42) does today.
Added test cases to the render command test function.
Very low, additive non-default behavior

[DDO-3575] Move ArgoCD `--mode` logic into Thelma

---

internal/thelma/app/config/profiles/argocd.yaml
internal/thelma/app/logging/logging.go

ArgoCD doesn't strip the back color markers from the output it shows, which makes Thelma's output really hard to read. I'm having to do that a lot to get it working in super-prod so I'd like to split this change out now to make it a bit easier.
I felt that manual testing was sufficient for a change as trivial as this -- I didn't want to spend the time trying to figure out how to capture and test for bash color codes. I checked default behavior, explicit true, and explicit false (the latter two using `THELMA_LOGGING_CONSOLE_COLOR`).
Low, by default there's no change and this just affects the `argocd` profile that's in use in super-prod.

[DDO-3575] Disable output coloring on ArgoCD

---

Dockerfile
internal/thelma/app/config/profiles/argocd.yaml
internal/thelma/app/platform/platform.go
internal/thelma/cli/environmentflags/parse_from_environment.go
internal/thelma/cli/environmentflags/parse_from_environment_test.go

- Use `workloadidentity` for IAP (`google` works too but requires the SA to have `roles/iam.serviceAccountOpenIdTokenCreator` on itself)
- Check for ArgoCD environment variables before trying to access the process owner ([ArgoCD sidecar plugins run as user 999](https://argo-cd.readthedocs.io/en/stable/operator-manual/config-management-plugins/#register-the-plugin-sidecar:~:text=Make%20sure%20that%20sidecar%20container%20is%20running%20as%20user%20999), which is unexpected enough that `user.Current()` has trouble -- checking for the environment variable first will bail us out before we get to that part)
- Use `flags.Set(name, value)` instead of `flag.Value.Set(value)` when parsing flags from the environment because the former actually makes `flags.Changed(name)` work while the latter …

[DDO-3575] Various tweaks for super-prod ArgoCD

---

internal/thelma/bee/bee.go
internal/thelma/bee/bee_test.go

Previously, we would hard refresh `terra-bee-generator` once and subsequently poll ArgoCD for 5 minutes to wait for the BEE's env generator had been created. Since the superprod migration, this step in the process has run into timeouts ([example](https://broadinstitute.slack.com/archives/CADM7MZ35/p1715088339735119)). See discussion [here](https://broadinstitute.slack.com/archives/CADM7MZ35/p1714398509502089) as well.
This PR attempts to address the issue by wrapping the refresh-poll step in up to 10 retries, and timing out the polling after 1 minute instead of 5 in order to force a hard refresh.
I was able to create a BEE running local Thelma off this PR. This PR also includes unit test updates.

[DDO-3660] Retry BEE env generator creation

---

internal/thelma/toolbox/argocd/argocd.go
internal/thelma/toolbox/argocd/argocd_test.go

This PR makes the following adjustments to Thelma's ArgoCD retry logic:
* **Bump sync operation timeout from 10 minutes to 15 minutes**. We've seen lots of sync operation timeouts lately that in [some cases](https://broadinstitute.slack.com/archives/CADM7MZ35/p1715088927043469) are non-fatal (the sync terminates eventually); this gives the BEE sync a bit longer to complete while we continue optimizing the server.
* **Retry all failed commands by default** instead of the previous behavior, which was retrying a specific list of known errors. This will specifically catch the 500 errors we've seen lately, and also allows us to stop playing whackamole if ArgoCD upgrades and the client error messages change. For 90% of calls this is harmless; I added an exception for timeout errors, because if …

[DDO-3664] Some adjustments to ArgoCD retry behavior

---

internal/thelma/utils/schedule/schedule.go
internal/thelma/utils/schedule/schedule_test.go

@jyang-broad and I discovered a bug in the BEE apply schedule job where BEEs with west coast working hours schedules (offline at 9pm EST or later) are never shut off. This appears to be due to a time zone comparison issue. Schedules are in the BEE creator's local time zone, and Thelma-in-GHA runs in UTC, causing a subset of the date comparisons to fail.

[DDO-3692] Fix bug preventing some BEEs from being shut down

---

internal/thelma/clients/iap/browser-provider.go
internal/thelma/toolbox/argocd/argocd.go

1. Thelma mutexes usage of the browser / local server pairing for getting IAP credentials -- it runs sequentially for authenticating to different project. `credentials.TokenProvider`'s got a ton of concurrency control already so blocking like this in an issuer function is fine 
2. Thelma sets up each local server instance using a local mux router, not the default global one (this is actually the issue @mflinn-broad was hitting, but the first fix still improves UX because now there's not a flurry of browser windows)
Local; deleted my credentials folder and ran it.
Very low
https://github.com/broadinstitute/thelma/pull/297 did such a great job of retrying everything that it even retries the fully-expected-to-error "is my auth valid" request to ArgoCD that's embedded in the ArgoCD client. …

[DDO-3687] [DDO-3788] Fixes for local Thelma browser auth

---

internal/thelma/cli/commands/render/render_command.go
internal/thelma/cli/commands/render/render_command_test.go
internal/thelma/render/helmfile/cmd.go
internal/thelma/render/helmfile/helmfile.go
internal/thelma/render/render.go
scripts/install-runtime-deps.sh

I ran into an issue where a a third party chart I was attempting to work with enforces a `kubeVersion` constraint in it's `Chart.yaml`. This has unfortunate interaction where because helm template doesn't actually run it against a live k8s server the kubeVersion will default to a hard coded value that is determined by the version of the k8s client library in the helm binary in runtime deps. Previously this chart would fail to render with `Error: chart requires kubeVersion: >= 1.23.0-0 which is incompatible with Kubernetes v1.20.0`. With these changes I am able to render the chart locally.
In our particular case this kubeVersion that gets defaulted to is `1.20.0` which is quite old. However both helm and helmfile expose a `--kube-version` flag in their template commands that can override …

Add support for propagating --kube-version flag down to helmfile template executions

---

internal/thelma/bee/seed/seed_step_4_register_test_users.go

For some reason, Google Workspace API calls that have worked well for years [started failing yesterday](https://broadinstitute.slack.com/archives/C03GMG4DUSE/p1717012586622649) during BEE creates. However, things seem to succeed on retry (we think?). The retry results in a 409 conflict from Sam, which is intentionally excluded from the retry logic in the orch client, but is not treated as an ignorable error by the BEE seed code. This PR makes it ignore-able.
We have an open Google Workspaces support ticket to figure out why these API calls have suddenly started returning 400 errors.
I tested with a local BEE create, it seemed to ignore the 409-on-retry successfully.

[DDO-3709] Hacky work-around for recent BEE seed failures

---

internal/thelma/bee/seed/config.go
internal/thelma/bee/seed/unseed_step_1_unregister_all_users.go

`thelma bee unseed` pulls the Sam database credentials from Vault at runtime. This PR updates it to pull from the some K8s secret used by the Sam pod instead.
This particular area of Thelma does not have unit test coverage, so I did a manual unseed. It worked, successfully pulling all registered users from the test user database and unregistering them in my BEE.
```
15:09 INF george.authdomain@quality.firecloud.org:              success status=Unregistered t=2s
15:09 INF ron.weasley@quality.firecloud.org:                    success status=Unregistered t=2s
15:09 INF gregory.goyle@quality.firecloud.org:                  success status=Unregistered t=2s
15:09 INF harry.potter@quality.firecloud.org:                   success status=Unregistered t=2s
15:09 INF …
```

[DDO-3723] Remove `thelma bee unseed` Vault dependency

---

internal/thelma/bee/seed/config.go
internal/thelma/clients/google/google.go

Update Thelma to pull SA keys from K8s secrets instead of Vault during BEE seeding.
This portion of Thelma does not have unit tests; I successfully ran `bee unseed` and `bee seed` against my BEE locally.

[DDO-3723] Eliminate uses of Vault in `thelma bee seed`

---

internal/thelma/bee/seed/config.go

Update to default k8s secret name where WSM's service account credentials are stored following https://github.com/broadinstitute/terra-helmfile/pull/5790.
This should be merged after the above linked pr.

Update default k8s secret name for WSM credentials in BEE seeding

---

scripts/install-runtime-deps.sh

Now that https://github.com/broadinstitute/terra-helmfile/pull/5801 has been merged, newer versions of Helm are okay with terra-helmfile. Upgrades Helm, Helmfile, and Helm Docs to latest.
I ran this in terra-helmfile:
```
thelma render -r ALL -e prod --parallel-workers 3 -d output/old
```
Then made this Thelma tweak, and from Thelma's repo:
```
rm -rf ./output
make build
./output/bin/thelma render -r ALL -e prod --parallel-workers 3 -d /Users/jwarren/src/terra-helmfile/output/new
```
Then back in terra-helmfile:
```
diff -bur output/old output/new
```
It showed no diff. I went and manually messed up one of the new manifests to confirm that this command would've highlighted any differences.
Low but dependency risk is never zero. I'm going to make very sure to fully cycle the repo server …

[DDO-3834] Upgrade Helm deps

---

internal/thelma/clients/slack/slack.go

Vault brownout testing revealed an error in the Thelma's slack message sending functionality where a null pointer deref occurs if a certain vault path doesn't exist, but the error from the vault api is being swallowed somewhere which resulted in segfault trying to inspect the error response. 
Solution is to temporarily flag off the slack token retrieval to unblock bee creation while we work on porting this functionality to GSM. This is a non-critical code path that just sends people running thelma locally the result of their bee operations over slack when complete.
Tested by running a bee creation with a local build of thelma built from this branch which succeeded and confirmed from logs that problematic code path was not traversed.

[DDO-3841] Temporarily Disable Slack Client due to segfault in Vault client trigered from brownout test

---

Dockerfile
internal/thelma/charts/mirror/mirror.go
internal/thelma/charts/repo/index/index.go
internal/thelma/clients/google/bucket/logging.go
internal/thelma/state/providers/sherlock/state_loader_test.go

Infosec wants us to use a blessed image if possible because that makes it easier to manage and report vulnerabilities.
Appsec doesn't want to make a blessed version of the raw Alpine image we currently use because it would be more overhead for them.
Seems a happy medium is to use their blessed _Python_ Alpine image. Denis suggested trying to remove Python from the image, but that seems error-prone to me: I want to avoid complexity here because this is already complex enough.
Denis did say that we can remove the OS update commands from the Dockerfile.
It seems golangci-lint got updated and now has some new rules. I've fixed the linting issues here for brevity.
[I opened a terra-helmfile PR using this branch of Thelma](https://github.com/broadinstitute/terra-helmfile/pull/5829) to test that …

[DDO-3849] Use Appsec's Blessed Python Base Image

---

internal/thelma/bee/seed/config.go
internal/thelma/bee/seed/seed_step_2_register_sa_profiles.go

Update thelma to auto-register the `teaspoons-qa` user if the `teaspoons` chart exists. (This is part of the effort to rename tsps -> teaspoons).

[DDO-3937] Register new teaspoons-qa SA

---

internal/thelma/bee/cleanup/cleanup.go

Marc Talbott noticed today that some pubsub topic weren't being cleaned up.
https://broadinstitute.slack.com/archives/C029LTN5L80/p1736873760584309

[DDO-3976] Add new topic pattern to pubsub BEE cleanup step
